### PR TITLE
Update to RavenDB 3.5

### PR DESCRIPTION
**Pull request by mzoellner**
This just bumps up the version of RavenDB to make it compatible with 3.5.
It would be great if you could integrate it and push it to nuget.

### CODE REVIEW

**Comment by tobiaszuercher** [comment]
go for it!

**Comment by mj1856** [comment]
Sorry for the delay.  I'll look this over and get it published soon.  Thanks!

**Comment by di97mni** [comment]
Any plans for this PR to be merged?

**Comment by iamisti** [comment]
+1 Please go ahead, we need this to have support for RavenDB 3.5

**Comment by mj1856** [comment]
Sorry for the delay on this.  Merged.  Will release shortly.

**Comment by mj1856** [comment]
Released v3.5.0.  Thanks again.

**Comment by tobiaszuercher** [comment]
thank you.

if you need more ppls helping to manage, just contact me!

**Pull request merged**
